CREATE TYPE Active AS ENUM('UNSPECIFIED', 'OFF_LINE', 'ACTIVE', 'NOT_SEEN');
CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  active Active
);
CREATE TABLE IF NOT EXISTS messages (
  id BIGSERIAL PRIMARY KEY,
  sender_id INTEGER REFERENCES users(id),
  message_text VARCHAR(1000) NOT NULL,
  submit_date Date
);
